// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrendplusProdavnica.Infrastructure.Persistence;

#nullable disable

namespace TrendplusProdavnica.Infrastructure.Migrations
{
    [DbContext(typeof(TrendplusDbContext))]
    [Migration("20260410000002_AddAnalyticsEvents")]
    partial class AddAnalyticsEvents
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // AnalyticsEvent entity configuration
            modelBuilder.Entity("TrendplusProdavnica.Domain.Analytics.AnalyticsEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventData")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("EventTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("EventType")
                        .HasColumnType("smallint");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("PageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReferrerUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EventTimestamp")
                        .HasDatabaseName("IX_analytics_events_timestamp");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_analytics_events_eventtype");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_analytics_events_productid");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_analytics_events_sessionid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_analytics_events_userid");

                    b.HasIndex("EventType", "EventTimestamp")
                        .HasDatabaseName("IX_analytics_events_type_timestamp");

                    b.HasIndex("ProductId", "EventType")
                        .HasDatabaseName("IX_analytics_events_product_eventtype");

                    b.ToTable("analytics_events", "analytics");
                });

#pragma warning restore 612, 618
        }
    }
}
